### ISSUE TITLE
Blurry Background Not Available in Pod

### ISSUE THREAD

**Issue by thephatp** [nimati/FCAlertView#21]
Any chance you'll be adding this to the pod soon?

**Comment by nimati** [comment]
Hi @thephatp,

Thanks for getting in touch. Absolutely! I'll be adding another feature from the list of upcoming features soon, which means it should be out within the next couple of days. I will let you know when it is.

Cheers,
Nima

**Comment by thephatp** [comment]
Thanks, and I know this isn't the right place, but I need to say it somewhere--this customized alert view is **incredible** both from a design _and_ from a customization perspective. It's exactly what I've been looking for, and I greatly appreciate all of the work you have done!!

**Comment by nimati** [comment]
@thephatp No worries at all! And I'm very glad to hear that, Thanks for saying it! It's exactly because of developers like you that I put a lot of effort and work into it to make sure it's useful and beautiful 👍 Be sure to stay posted on new libraries as well, and feel free to [email me](mailto:nttahami@gmail.com) any suggestion you have!

**Comment by nimati** [comment]
@thephatp You can now use CocoaPod version 1.1.2 along with other new features including blur :) Enjoy! README.md has been updated with instructions on how to use them.
