### ISSUE TITLE
Missing error message issue

### ISSUE THREAD

**Issue by magnett** [nimati/FCAlertView#27]
First of all thank you for this great control. Really love it!
The issue:
I know that the message of the alert should never be nil. 
I used FCAlertView to display some error messages coming from a web service. They should never be nil but i forgot to validate them. What came up is in the screenshot below. 
I think that you should never ever show something like this to a user. It's 100 times better to present an empty label than showing that to a user. 
Now that i saw it, i validate any message and in case it's nil i set some text, however i think you should address this.
Thanks again!
![screen shot 2016-11-07 at 14 07 36](https://cloud.githubusercontent.com/assets/1730803/20058364/49aa3352-a4f9-11e6-98b1-9f5cc3edbbe2.png)

**Comment by nimati** [comment]
Hi @magnett,

Thank you for bringing this to my attention. This was actually one of the first
checks I put in place, mostly for development purposes, as you are absolutely 
right, the user should not see that since that wouldn't make sense to them at all.

I went ahead and removed that text so empty subtitles are allowed now, however, in
place I've put a warning that will be NSLogged so at least the developers would be
able to know. Please use FCAlertView V1.2.5+ to see this fix.
Thank you for using FCAlertView!

Cheers 👍
