### ISSUE TITLE
Alert is dismissed on UIKeyboard hide

### ISSUE THREAD

**Issue by DrBeak1** [nimati/FCAlertView#33]
When keyboard is dismissed (textField.resignFirstResponder) the alert is auto-dismissed. 

UIViewController is setup to monitor uikeyboard show/hide. I'm animating a button up/down to follow top of uikeyboard using nslayoutconstraint, whose animation requires view.setNeedsLayout and then view.layoutIfNeeded -- maybe that is causing this?

Issue is resolved if I use `[alert showAlertInWindow: ...]`

**Comment by nimati** [comment]
Hi @DrBeak1 

Hmm interesting. Thanks for bringing this up... I've noticed other functions to present the alert (rather than ```[alert showAlertInWindow: ...]```) and the keyboard sometimes does strange stuff. Please continue to use showAlertInWindow for your case. Let me know if there's anything else and thanks for using FCAlertView!

Cheers,
Nima
